// src/app/components/ChartComponent.vue
<script setup lang="ts">
import { onBeforeMount } from 'vue'
import { Line } from 'vue-chartjs'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip
} from 'chart.js'

const props = defineProps(['chartStatistics'])

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip)

const chartOptions = {
  responsive: true
}

const chartData = {
  labels: [],
  datasets: []
}

onBeforeMount(() => {
  Object.assign(chartData, {
    labels: Object.keys(props.chartStatistics),
    datasets: [
      {
        data: Object.values(props.chartStatistics),
        label: 'Amount',
        fill: false,
        tension: 0.1,
        borderColor: '#600000',
        backgroundColor: '#600000'
      }
    ]
  })
})
</script>

<template>
  <div class="d-block">
    <Line :data="chartData" :options="chartOptions" class="w-100"> </Line>
  </div>
</template>

// src/app/main/components/chart/chart.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ChartConfiguration, ChartOptions } from 'chart.js';

@Component({
  selector: 'app-chart',
  standalone: false,
  templateUrl: './chart.component.html',
  styleUrl: './chart.component.scss',
})
export class ChartComponent implements OnInit {
  @Input()
  statistics: object = {};

  keys: string[] = [];
  lineChartData: ChartConfiguration<'line'>['data'] = {
    labels: [],
    datasets: [],
  };

  ngOnInit() {
    this.keys = Object.keys(this.statistics);

    this.lineChartData = {
      labels: this.keys,
      datasets: [
        {
          data: Object.values(this.statistics),
          label: 'Amount',
          fill: false,
          tension: 0.1,
          borderColor: '#600000',
          backgroundColor: '#600000',
        },
      ],
    };
  }

  title = 'statistics-chart';

  public lineChartOptions: ChartOptions<'line'> = {
    responsive: false,
  };
  public lineChartLegend = false;
}

<div class="d-block">
  <canvas
    baseChart
    [type]="'line'"
    [data]="lineChartData"
    [options]="lineChartOptions"
    [legend]="lineChartLegend"
    class="w-100"
  >
  </canvas>
</div>
